### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ConnectedSystems** [JuliaPlots/Plots.jl#4792]
## Details

This may not be a Plots.jl issue but not sure where else to report this.

I've been having trouble compiling a custom sysimage via VS Code's build task (v1.47.2).
The process fails with error: "invalid redefinition of constant UnitfulExt"

If I remove Plots.jl from my environment however, the error disappears.

Dependencies in my environment:

```toml
[deps]
AbstractGPs = "99985d1d-32ba-4be9-9821-2ec096f28918"
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
Bootstrap = "e28b5b4c-05e8-5b66-bc03-6f0c0a0a06e0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
CodecBzip2 = "523fee87-0ab8-5b00-afb7-3ecf72e48cfd"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FLoops = "cc61a311-1640-44b5-9fba-1b764f453329"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeoDataFrames = "62cb38b5-d8d2-4862-a48e-6a340996859f"
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
GeoStats = "dcc97b0b-8ce5-5539-9008-bb190f959ef6"
GeoStatsViz = "36492b79-4a51-4dff-89b6-31e03c9a81c2"
GeoTables = "e502b557-6362-48c1-8219-d30d308dcdb0"
Geodesy = "0ef565a4-170c-5f04-8de2-149903a85f3d"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
MATLAB = "10e44e05-a98a-55b3-a45b-ba969058deb6"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NamedDims = "356022a1-0364-5f58-8944-0da4b18d706f"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RData = "df47a6cb-8c03-5eed-afd8-b6050d6c41da"
ReefModEngine = "f4ffb74a-bba7-4ac3-ad08-f8621d7c6d1d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RelocatableFolders = "05181044-ff0b-4ac5-8273-598c1e38db00"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
SnoopCompile = "aa65fe97-06da-5843-b5b1-d5d13cad87d2"
SnoopCompileCore = "e2b509da-e806-4183-be48-004708413034"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Surrogates = "6fc51010-71bc-11e9-0e15-a3fcc6593c49"
SurrogatesAbstractGPs = "78aa1720-c2af-471b-b307-964fd38f9b5f"
SurrogatesPolyChaos = "50679fc6-c85c-4a6e-ac63-dc3c8bd8cb1c"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"
```

### Backends

This bug occurs on ( insert `x` below )

Backend      | yes | no  | untested
-------------|-----|-----|---------
gr (default) |  x  |     |
pythonplot   |     |     |
plotlyjs     |     |     |
pgfplotsx    |     |     |
unicodeplots |     |     |
inspectdr    |     |     |
gaston       |     |     |

### Versions

Plots.jl version: v1.38.16
Backend  version (`]st -m <backend(s)>`):
Output of `versioninfo()`:
